repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --config, pyproject.toml]
        exclude: ^(examples|docs)/
      - id: ruff-format
        args: [--config, pyproject.toml]
        exclude: ^(examples|docs)/
  - repo: local
    hooks:
      - id: pixi-install
        name: Keep lockfile up-to-date
        entry: pixi install
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
