# This is necessary for nxviz as matplotlib is involved.
# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 5 # give xvfb some time to start

language: python
matrix:
  include:
    - python: 3.5  # we don't actually use this
      env: PYTHON_VERSION=3.6

    - python: 3.5  # we don't actually use this
      env: PYTHON_VERSION=3.7

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge

  # Useful for debugging any issues with conda
  - conda info -a

  # Install Python, py.test, and required packages.
  - conda env create -f environment.yml
  - conda install python=$PYTHON_VERSION matplotlib-base
  - source activate nxviz
  - python setup.py install

script:
  # Your test script goes here
  - pycodestyle .
  - py.test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
