name: Code style checks

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
      - name: Run pre-commit
        run: uvx pre-commit run --all-files
