name: Build documentation

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build documentation

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: docs

      - name: Build docs
        run: pixi run build-docs

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
