name: Build documentation

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: docs

      - name: Build docs
        run: pixi run -e docs build-docs

      - name: Deploy to GitHub Pages
        if: github.ref_name == 'master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1.8.1
        with:
          source-dir: site
          preview-branch: gh-pages
